const MAIN_SCREEN_APP_BAR_TITLE = "Discover";
const  BEST_POPULAR_MOVIES_AND_SERIALS="Best Popular Movies and Serials";
const MAIN_SCREEN_CHECK_MOVIE_SHOW_TIME="Check Movie\nShow Times";
const MAIN_SCREEN_SEE_MORE="See More";
const SHOW_CASES_TITLE="SHOWCASES";
const SHOW_CASES_SEE_MORE="MORE SHOWCASES";
const BEST_ACTOR_TITLE="BEST ACTORS";
const BEST_ACTOR_SEE_MORE="MORE ACTORS";

const MOVIE_DETAIL_SCREEN_ACTOR_TITLE="ACTORS";
const MOVIE_DETAIL_SCREEN_CREATOR_TITLE="CREATORS";
const MOVIE_DETAIL_SCREEN_CREATOR_SEE_MORE="MORE CREATORS";
const MOVIE_DETAIL_STORYLINE_TITLE="STORYLINE";